package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"Web-app/backend/internal/models"
	"context"
	"fmt"
)

// ID is the resolver for the id field.
func (r *carResolver) ID(ctx context.Context, obj *models.Car) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// CreateCar is the resolver for the createCar field.
func (r *mutationResolver) CreateCar(ctx context.Context, name string, brand string, pricePerDay float64, imageURL *string) (*models.Car, error) {
	img := ""
	if imageURL != nil {
		img = *imageURL
	}
	car := &models.Car{
		Name:        name,
		Brand:       brand,
		PricePerDay: pricePerDay,
		ImageUrl:    img,
		Available:   true,
	}
	if err := r.DB.Create(car).Error; err != nil {
		return nil, err
	}
	return car, nil
}

// UpdateCar is the resolver for the updateCar field.
func (r *mutationResolver) UpdateCar(ctx context.Context, id string, name *string, brand *string, pricePerDay *float64, available *bool, imageURL *string) (*models.Car, error) {
	var car models.Car
	// 1. Find the car in the database
	if err := r.DB.First(&car, id).Error; err != nil {
		return nil, fmt.Errorf("car not found")
	}

	// 2. Update fields only if they are provided (not null)
	updates := make(map[string]interface{})
	if name != nil {
		updates["name"] = *name
	}
	if brand != nil {
		updates["brand"] = *brand
	}
	if pricePerDay != nil {
		updates["price_per_day"] = *pricePerDay
	}
	if available != nil {
		updates["available"] = *available
	}
	if imageURL != nil {
		updates["image_url"] = *imageURL
	}

	// 3. Save updates to DB
	if err := r.DB.Model(&car).Updates(updates).Error; err != nil {
		return nil, err
	}

	return &car, nil
}


// DeleteCar is the resolver for the deleteCar field.
func (r *mutationResolver) DeleteCar(ctx context.Context, id string) (bool, error) {
	var car models.Car
	if err := r.DB.First(&car, id).Error; err != nil {
		return false, err
	}
	if err := r.DB.Delete(&car).Error; err != nil {
		return false, err
	}
	return true, nil
}

// Cars is the resolver for the cars field.
func (r *queryResolver) Cars(ctx context.Context) ([]*models.Car, error) {
	var cars []*models.Car
	if err := r.DB.Find(&cars).Error; err != nil {
		return nil, err
	}
	return cars, nil
}

// Car is the resolver for the car field.
func (r *queryResolver) Car(ctx context.Context, id string) (*models.Car, error) {
	panic(fmt.Errorf("not implemented: Car - car"))
}

// Car returns CarResolver implementation.
func (r *Resolver) Car() CarResolver { return &carResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type carResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
