package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"Web-app/backend/internal/models"
	"context"
	"fmt"
	"strconv"
	"time"
)

// ID is the resolver for the id field.
func (r *bookingResolver) ID(ctx context.Context, obj *models.Booking) (string, error) {
	return strconv.FormatUint(uint64(obj.ID), 10), nil
}

// StartDate is the resolver for the startDate field.
func (r *bookingResolver) StartDate(ctx context.Context, obj *models.Booking) (string, error) {
	return obj.StartDate.Format(time.RFC3339), nil
}

// EndDate is the resolver for the endDate field.
func (r *bookingResolver) EndDate(ctx context.Context, obj *models.Booking) (string, error) {
	return obj.EndDate.Format(time.RFC3339), nil
}

// ID is the resolver for the id field.
func (r *carResolver) ID(ctx context.Context, obj *models.Car) (string, error) {
	return fmt.Sprintf("%d", obj.ID), nil
}

// CreateCar is the resolver for the createCar field.
func (r *mutationResolver) CreateCar(ctx context.Context, name string, brand string, pricePerDay float64, imageURL *string) (*models.Car, error) {
	img := ""
	if imageURL != nil {
		img = *imageURL
	}
	car := &models.Car{
		Name:        name,
		Brand:       brand,
		PricePerDay: pricePerDay,
		ImageUrl:    img,
		Available:   true,
	}
	if err := r.DB.Create(car).Error; err != nil {
		return nil, err
	}
	return car, nil
}

// UpdateCar is the resolver for the updateCar field.
func (r *mutationResolver) UpdateCar(ctx context.Context, id string, name *string, brand *string, pricePerDay *float64, available *bool, imageURL *string) (*models.Car, error) {
	var car models.Car
	// 1. Find the car in the database
	if err := r.DB.First(&car, id).Error; err != nil {
		return nil, fmt.Errorf("car not found")
	}

	// 2. Update fields only if they are provided (not null)
	updates := make(map[string]interface{})
	if name != nil {
		updates["name"] = *name
	}
	if brand != nil {
		updates["brand"] = *brand
	}
	if pricePerDay != nil {
		updates["price_per_day"] = *pricePerDay
	}
	if available != nil {
		updates["available"] = *available
	}
	if imageURL != nil {
		updates["image_url"] = *imageURL
	}

	// 3. Save updates to DB
	if err := r.DB.Model(&car).Updates(updates).Error; err != nil {
		return nil, err
	}

	return &car, nil
}

// DeleteCar is the resolver for the deleteCar field.
func (r *mutationResolver) DeleteCar(ctx context.Context, id string) (bool, error) {
	var car models.Car
	if err := r.DB.First(&car, id).Error; err != nil {
		return false, err
	}
	if err := r.DB.Delete(&car).Error; err != nil {
		return false, err
	}
	return true, nil
}

// CreateBooking is the resolver for the createBooking field.
func (r *mutationResolver) CreateBooking(ctx context.Context, carID string, startDate string, endDate string, userEmail string) (*models.Booking, error) {
	sDate, err := time.Parse("2006-01-02", startDate)
	if err != nil {
		sDate, err = time.Parse(time.RFC3339, startDate)
		if err != nil {
			return nil, fmt.Errorf("invalid start date format, use YYYY-MM-DD")
		}
	}
	eDate, err := time.Parse("2006-01-02", endDate)
	if err != nil {
		eDate, err = time.Parse(time.RFC3339, endDate)
		if err != nil {
			return nil, fmt.Errorf("invalid end date format, use YYYY-MM-DD")
		}
	}

	cID, err := strconv.ParseUint(carID, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid car id")
	}

	booking := &models.Booking{
		CarID:     uint(cID),
		StartDate: sDate,
		EndDate:   eDate,
		UserEmail: userEmail,
		Status:    "confirmed",
	}

	if err := r.DB.Create(booking).Error; err != nil {
		return nil, err
	}

	// Update car availability
	r.DB.Model(&models.Car{}).Where("id = ?", cID).Update("available", false)

	// Preload Car for the response
	r.DB.Preload("Car").First(booking, booking.ID)

	return booking, nil
}

// Cars is the resolver for the cars field.
func (r *queryResolver) Cars(ctx context.Context) ([]*models.Car, error) {
	var cars []*models.Car
	if err := r.DB.Find(&cars).Error; err != nil {
		return nil, err
	}
	return cars, nil
}

// Car is the resolver for the car field.
func (r *queryResolver) Car(ctx context.Context, id string) (*models.Car, error) {
	var car models.Car
	if err := r.DB.First(&car, id).Error; err != nil {
		return nil, err
	}
	return &car, nil
}

// Bookings is the resolver for the bookings field.
func (r *queryResolver) Bookings(ctx context.Context) ([]*models.Booking, error) {
	var bookings []*models.Booking
	if err := r.DB.Preload("Car").Find(&bookings).Error; err != nil {
		return nil, err
	}
	return bookings, nil
}

// Booking returns BookingResolver implementation.
func (r *Resolver) Booking() BookingResolver { return &bookingResolver{r} }

// Car returns CarResolver implementation.
func (r *Resolver) Car() CarResolver { return &carResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type bookingResolver struct{ *Resolver }
type carResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
